import IKorisnik from "@/app/interfaces/KorisnikInterface";

const korisnici: IKorisnik[] = [
  {
    id: 1,
    ime: "Marko",
    prezime: "Jovanović",
    email: "marko.jovanovic@gmail.com",
    lozinka: "marko123",
    telefon: "+381 63 123 4567",
    datumRodjenja: new Date("1990-05-14"),
    adresa: "Knez Mihailova 12",
    grad: "Beograd centar",
    vozackaDozvola: "BG-123456",
    slika: "/images/users/marko.jpg",
    uloga: "korisnik",
    datumRegistracije: new Date("2023-01-10"),
  },
  {
    id: 2,
    ime: "Ana",
    prezime: "Petrović",
    email: "ana.petrovic@gmail.com",
    lozinka: "ana123",
    telefon: "+381 64 234 5678",
    datumRodjenja: new Date("1995-08-22"),
    adresa: "Bulevar Oslobođenja 45",
    grad: "Novi Sad",
    vozackaDozvola: "NS-234567",
    slika: "/images/users/ana.jpg",
    uloga: "korisnik",
    datumRegistracije: new Date("2023-03-15"),
  },
  {
    id: 3,
    ime: "Stefan",
    prezime: "Milošević",
    email: "stefan.milosevic@gmail.com",
    lozinka: "stefan123",
    telefon: "+381 65 345 6789",
    datumRodjenja: new Date("1988-11-03"),
    adresa: "Vojvode Mišića 8",
    grad: "Niš",
    vozackaDozvola: "NI-345678",
    slika: "/images/users/stefan.jpg",
    uloga: "korisnik",
    datumRegistracije: new Date("2023-06-20"),
  },
  {
    id: 4,
    ime: "Jelena",
    prezime: "Nikolić",
    email: "jelena.nikolic@gmail.com",
    lozinka: "jelena123",
    telefon: "+381 66 456 7890",
    datumRodjenja: new Date("1993-02-17"),
    adresa: "Cara Dušana 33",
    grad: "Kragujevac",
    vozackaDozvola: "KG-456789",
    slika: "/images/users/jelena.jpg",
    uloga: "korisnik",
    datumRegistracije: new Date("2023-09-05"),
  },
  {
    id: 5,
    ime: "Nikola",
    prezime: "Đorđević",
    email: "nikola.djordjevic@gmail.com",
    lozinka: "nikola123",
    telefon: "+381 69 567 8901",
    datumRodjenja: new Date("1985-07-30"),
    adresa: "Trg Slobode 2",
    grad: "Subotica",
    vozackaDozvola: "SU-567890",
    slika: "/images/users/nikola.jpg",
    uloga: "korisnik",
    datumRegistracije: new Date("2024-01-12"),
  }
];

export default korisnici;
